# `man 5 sway`

default_border pixel 2
default_floating_border pixel 2

client.focused #2a2422 #5a504c #e6d5c2 #99af6b #ea9875
client.unfocused #5a504c #2a2422 #e6d5c2
client.focused_inactive #5a504c #5a504c #a09384

gaps inner 10

# vim: ft=swayconfig
