#!/bin/sh

# Note: ensure this file sourced after profile

# Command verbosity for safety
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -Iv" \
    mkdir="mkdir -pv"

# Colorize commands
alias \
    l="eza -Al --no-quotes --color=auto --group-directories-first" \
    ls="eza --color=auto --group-directories-first --git --icons --long --octal-permissions --no-permissions --mounts --time-style='+%Y %b %d %H:%M'" \
    grep="grep --color=auto" \
    ip="ip -color=auto"

# Abbreviate commands
alias \
    fpk="flatpak" \
    g="git" \
    v="nvim" \
    lzd="lazydocker"

# Use neovim as a man pager!
man() {
    if [ -z "${1}" ]; then
       /bin/man
       return
    fi

    if /bin/man -w "${1}" 2> /dev/null; then
        nvim -c "Man ${1} | only!"
    else
        /bin/man "${1}"
    fi
}

# Copy file to clipboard
cpc() {
    if [ -n "${1}" ] && [ -f $1 ]; then
        wl-copy < $1
    else
        printf "No such file or directory: '%s'\n" $1
        return 1
    fi
}

sd() {
    for arg in "$@"; do
        case "$1" in
            -g | --git)
                git=1
                shift
                ;;
            -v | --verbose)
                verbose=1
                shift
                ;;
            *)
                echo "unrecognized argument: '$1'" >&2
                return 1
                ;;
        esac
    done

    cmdstring="fd --no-ignore -t d"
    selected_dir=$(fd --no-ignore -t d | fzf)

    if [ -z "$selected_dir" ]; then
        exit 0
    fi

    cd $selected_dir
}
