#!/bin/sh

# Note: ensure this file sourced after profile

# Command verbosity for safety
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -Iv" \
    mkdir="mkdir -pv" \
    up="cd .."

alias \
    ls="ls --color=auto --group-directories-first --time-style=long-iso" \
    ll="ls -l"

# Abbreviate commands
alias \
    fpk="flatpak" \
    g="git" \
    v="nvim" \
    org="nvim $HOME/Documents/org +'Org agenda a'"

alias \
    zb="zig build" \
    zbr="zig build run" \
    zbt="zig build test"

alias \
    dcp="docker compose"

# https://sw.kovidgoyal.net/kitty/faq/#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-or-functional-keys-like-arrow-keys-don-t-work
alias \
    kssh="kitten ssh"

alias \
    sv="swappy -f "

# Copy file to clipboard
cpc() {
    if [ -n "${1}" ] && [ -f $1 ]; then
        wl-copy < $1
    else
        printf "No such file or directory: '%s'\n" $1
        return 1
    fi
}

sd() {
    for arg in "$@"; do
        case "$1" in
            -g | --git)
                git=1
                shift
                ;;
            -v | --verbose)
                verbose=1
                shift
                ;;
            *)
                echo "unrecognized argument: '$1'" >&2
                return 1
                ;;
        esac
    done

    cmdstring="fd --no-ignore -t d"
    selected_dir=$(fd --no-ignore -t d | fzf)

    if [ -z "$selected_dir" ]; then
        exit 0
    fi

    cd "$selected_dir" || return 1
}

hexdec() {
    [ -n "$1" ] && case "$1" in
        0x*) printf '%d\n' "$1" ;;
        *) printf '%d\n' "0x$1" ;;
    esac
}

dechex() {
    [ -n "$1" ] && printf '%x\n' "$1"
}

gogit() {
    remote=$1

    if [ -z "$1" ]; then
        remote="origin"
    fi

    url="$(git remote get-url ${remote})"

    case "${url}" in
        http://*)
            echo "using http"
            ;;
        https://*)
            echo "using https"
            ;;
        *)
            echo "Unsupported protocol (likely: ${url}" >&2
            return 1
            ;;
    esac

    firefox --new-tab "${url}"
}

# path lines - split each directory in PATH into newlines
pathl() {
    echo "$PATH" | sed 's/:/\n/g'
}
