#!/bin/sh

[[ -f ~/.bashrc ]] && . ~/.bashrc

############################
# Setup XDG Base Directory #
############################
if [ -z "$XDG_CONFIG_HOME" ]; then
    export XDG_CONFIG_HOME="$HOME/.config"
fi

if [ -z "$XDG_CACHE_HOME" ]; then
    export XDG_CACHE_HOME="$HOME/.cache"
fi

if [ -z "$XDG_DATA_HOME" ]; then
    export XDG_DATA_HOME="$HOME/.local/share"
fi

if [ -z "$XDG_STATE_HOME" ]; then
    export XDG_STATE_HOME="$HOME/.local/state"
fi

if [ -z "$XDG_RUNTIME_DIR" ]; then
    uid=$UID
    if [ -z "$UID" ]; then
        uid=$(id -u)
    fi

    export XDG_RUNTIME_DIR="/run/user/$uid"
fi

######################
# Setup applications #
######################
export BROWSER="zen-browser"
export EDITOR="nvim"
export TERM="ghostty"
export TERMINAL="$TERM"
export MANWIDTH=80
export MANPAGER="nvim +Man!"
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"


#############
# GTK Theme #
#############
export GTK_THEME=Adwaita:dark

#################
# Clean up home #
#################
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export GOPATH="$XDG_DATA_HOME/go"
# export HISTFILE="$XDG_DATA_HOME/history" # Note: defer to shell config for this
export DOTNET_INSTALL_DIR="$XDG_DATA_HOME/dotnet"
export DOTNET_ROOT="$DOTNET_INSTALL_DIR"
export DOTNET_HOME="$DOTNET_ROOT"
export DOTNET_TOOL_ROOT="$DOTNET_ROOT/tools"
export COMPOSER_HOME="$XDG_CONFIG_HOME/composer"
export NVM_DIR="$XDG_DATA_HOME/nvm"

##############
# Setup PATH #
##############

# Append "$1" to $PATH when not already in.
# Taken from /etc/profile
append_path () {
    test -d "$1" || return 1

    case ":$PATH:" in
        *:"$1":*)
            ;;
        *)
            PATH="${PATH:+$PATH:}$1"
    esac
}

append_path "$CARGO_HOME/bin"
append_path "$XDG_DATA_HOME/dotnet"
append_path "$DOTNET_ROOT/tools"
append_path "$HOME/.yarn/bin"
append_path "$COMPOSER_HOME/vendor/bin"

# This adds ~/.local/bin and all immediate subdirs (non-recursively) to PATH
local_bin_paths="$(find ~/.local/bin -maxdepth 1 -type d -printf %p:)"
PATH="$PATH:${local_bin_paths%%:}"

export PATH

##########################
# Other environment vars #
##########################
export DOTNET_CLI_TELEMETRY_OUTPUT='true'

################
# Run programs #
################
# if [ -z "$DISPLAY" ] && [ "$XDG_VTNR" = 1 ]; then
#     mkdir -p "$HOME/.var/log/sway"
#     exec sway > "$HOME/.var/log/sway/sway.log" 2> "$HOME/.var/log/sway/sway_err.log"
# fi
