#!/bin/sh

############################
# Setup XDG Base Directory #
############################
if [ -z "$XDG_CONFIG_HOME" ]; then
    export XDG_CONFIG_HOME="$HOME/.config"
fi

if [ -z "$XDG_CACHE_HOME" ]; then
    export XDG_CACHE_HOME="$HOME/.cache"
fi

if [ -z "$XDG_DATA_HOME" ]; then
    export XDG_DATA_HOME="$HOME/.local/share"
fi

if [ -z "$XDG_STATE_HOME" ]; then
    export XDG_STATE_HOME="$HOME/.local/state"
fi

if [ -z "$XDG_RUNTIME_DIR" ]; then
    uid=$UID
    if [ -z "$UID" ]; then
        uid=$(id -u)
    fi

    export XDG_RUNTIME_DIR="/run/user/$uid"
fi

######################
# Setup applications #
######################
export EDITOR="nvim"
export TERMINAL="kitty"


#################
# Clean up home #
#################
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export GOPATH="$XDG_DATA_HOME/go"
export HISTFILE="$XDG_DATA_HOME/history"
export DOTNET_INSTALL_DIR="$XDG_DATA_HOME/dotnet"
export DOTNET_ROOT="$DOTNET_INSTALL_DIR"
export DOTNET_HOME="$DOTNET_ROOT"
export DOTNET_TOOL_ROOT="$DOTNET_ROOT/tools"
export COMPOSER_HOME="$XDG_CONFIG_HOME/composer"

###############
# zsh history #
###############
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt hist_reduce_blanks
export HISTSIZE=1000000
export SAVEHIST=$HISTSIZE

##############
# Setup PATH #
##############
CREATE="1"
NO_CREATE="0"

# add_path: append a path to the PATH variable
# $1: the path to append to PATH
# $2: create the path
add_path() {
    if ! [ -d "$1" ]; then
        if [ -n "$2" ] && [ "$2" != "$NO_CREATE" ]; then
            mkdir -pv $1
            p="$1"
        fi
    else
        p="$1"
    fi

    PATH="$PATH:$p"
}

add_path "$HOME/.local/bin" "$CREATE"
add_path "$CARGO_HOME/bin" "$NO_CREATE"
add_path "$XDG_DATA_HOME/dotnet"
add_path "$DOTNET_ROOT/tools"
add_path "$HOME/.yarn/bin"
add_path "$COMPOSER_HOME/vendor/bin"

node_version=$(node --version 2> /dev/null)
if [ -n "$node_version" ]; then
    # https://flaviocopes.com/where-npm-install-packages/
    add_path "$HOME/.nvm/versions/node/$node_version/bin"
fi


# This adds all subdirs of ~/.local/bin to path
PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"

export PATH

##########################
# Other environment vars #
##########################
export DOTNET_CLI_TELEMETRY_OUTPUT='true'

if [ -r "$CARGO_HOME/env" ]; then
    source "$CARGO_HOME/env"
fi

#######
# NVM #
######
if [ -f /usr/share/nvm/init-nvm.sh ]; then
    source /usr/share/nvm/init-nvm.sh
fi

if [ -z "$DISPLAY" ] && [ "$XDG_VTNR" = 1 ]; then
    mkdir -p "$HOME/.var/log/hypr"
    exec Hyprland > "$HOME/.var/log/hypr/hyprland.log" 2> "$HOME/.var/log/hypr/hyprland_err.log"
fi
