# `man 5 sway-output`

output "DP-3" {
    bg /home/wes/.local/share/wallpaper fill
    mode 1920x1080@60Hz
    pos -1080 -370
    transform 270
}

output "HDMI-A-1" {
    bg /home/wes/.local/share/wallpaper fill
    mode 2560x1440@60Hz
    pos 0 0
}

# vim: ft=swayconfig
