# Halloy config.
#
# For a complete list of available options,
# please visit https://halloy.chat/configuration.html

theme = "Gruvbox"

[servers.liberachat]
nickname = "weskoerber"
username = "weskoerber"
realname = "Wes Koerber"
server = "irc.libera.chat"
channels = ["#libera", "#sway", "#wlroots", "#zig"]
