#!/usr/bin/zsh

install_antigen() {
    if [ -d "${XDG_DATA_HOME:-$HOME/.local/share}/antigen" ]; then
        echo "Updating antigen..."
        rm -rf "${XDG_DATA_HOME:-$HOME/.local/share}/antigen"
    else
        echo "Installing antigen..."
    fi

    curl -L -s --create-dirs git.io/antigen-nightly --output "${XDG_DATA_HOME:-$HOME/.local/share}/antigen/antigen.zsh"
    # chmod +x "${XDG_DATA_HOME:-$HOME/.local/share}/antigen/antigen.zsh"
}

install_p10k() {

    if [ -d "${XDG_DATA_HOME:-$HOME/.local/share}/powerlevel10" ]; then
        echo "Updating powerlevel10k"
        rm -rf "${XDG_DATA_HOME:-$HOME/.local/share}/powerlevel10"
    else
        echo "Installing powerlevel10k..."
    fi

    git clone --quiet --depth=1 https://github.com/romkatv/powerlevel10k.git \
        "${XDG_DATA_HOME:-$HOME/.local/share}/powerlevel10"
}

get_dotnet_install() {
    if [ -f "$HOME/.local/bin/dotnet-install" ]; then
        echo "Updating dotnet-install..."
        rm "$HOME/.local/bin/dotnet-install"
    else
        echo "Installing dotnet-install..."
    fi

    curl -L -s https://dot.net/v1/dotnet-install.sh --output "$HOME/.local/bin/dotnet-install"

}

if ! [ -f "${XDG_STATE_HOME:-$HOME/.local/state}/.first_run_complete" ]; then
    echo "First run detected. Setting things up..."
    install_antigen
    get_dotnet_install

    echo "First run completed!"
    echo "Note: You may need to log out in order for changes to take effect."
    echo "To run first run setup again, remove the following file:"
    echo "    ${XDG_STATE_HOME:-$HOME/.local/state}/.first_run_complete"
    echo ""

    date +"%s" > ${XDG_STATE_HOME:-$HOME/.local/state}/.first_run_complete
fi
